version: "3.8"
services:
  spark:
    build:
      context: .                      # Racine du proket 
      dockerfile: docker/Dockerfile          # Chemin du Dockerfile
    container_name: spark_local
    volumes:
      - ./data:/app/data
      - ./intermediate:/app/intermediate 
    working_dir: /app  
    entrypoint: [ "bash" ] 

  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/key.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./spark:/opt/airflow/scripts
      - ./gcp-creds/key.json:/opt/airflow/key.json
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/key.json
    volumes:
      - ./dags:/opt/airflow/dags  
      - ./data:/opt/airflow/data
      - ./spark:/opt/airflow/scripts
      - ./gcp-creds/key.json:/opt/airflow/key.json
    command: >
      bash -c "airflow scheduler"

volumes:
  postgres_db: